# Generated by Django 5.0.4 on 2024-05-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='apppointment_id',
            new_name='appointment_id',
        ),
    ]
