# Generated by Django 5.0.4 on 2024-05-24 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('days', models.CharField(max_length=50)),
                ('start_time', models.TimeField(default='00:00')),
                ('end_time', models.TimeField(default='00:00')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=50)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_app.doctors')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
