# Generated by Django 5.0.4 on 2024-06-04 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_app.doctors'),
        ),
    ]
