# Generated by Django 5.0.4 on 2024-04-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='apppointment_id',
            field=models.CharField(default='A000', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
