# Generated by Django 5.0.4 on 2024-04-19 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0002_appointment_apppointment_id_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doctors',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Males'), ('F', 'Females'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
