# Generated by Django 5.0.4 on 2024-04-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0004_alter_doctors_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
