# Generated by Django 5.0.4 on 2024-04-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0005_alter_doctors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doc-pics/'),
        ),
    ]
