# Generated by Django 5.0.4 on 2024-04-20 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0007_alter_doctors_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
