# Generated by Django 5.0.4 on 2024-04-27 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0008_alter_doctors_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
