# Generated by Django 5.0.4 on 2024-04-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0009_alter_patients_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='statu',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In_Progress', 'In Progress'), ('Completed', 'Completed')], default='Select', max_length=20),
        ),
    ]
