# Generated by Django 5.0.4 on 2024-04-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0010_appointment_statu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='statu',
            new_name='status',
        ),
    ]
